# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contents', models.TextField(default='')),
                ('authors', models.ManyToManyField(to='noveltorpedo.Author')),
            ],
        ),
        migrations.CreateModel(
            name='StoryAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=511)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noveltorpedo.Story')),
            ],
        ),
    ]
