language: python
services:
  - postgresql
  - elasticsearch
python:
  - "3.5"
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.4/elasticsearch-2.4.4.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.4.deb && sudo service elasticsearch restart
install:
  - pip install -q django
  - pip install -q elasticsearch
  - pip install -q yaml
  - pip install -q psycopg2
before_script:
  - sleep 10
  - psql -c 'create database noveltorpedo;' -U postgres
