language: python
services:
  - postgresql
  - elasticsearch
python:
  - "3.5"
install:
  - pip install -q django
  - pip install -q elasticsearch
  - pip install -q yaml
  - pip install -q psycopg2
before_script:
  - sleep 10
  - psql -c 'create database noveltorpedo;' -U postgres
