language: python
branches:
  - master
  - travis
  - SB_scraper
services:
  - postgresql
python:
  - "3.5"
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.4/elasticsearch-2.4.4.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.4.deb && sudo service elasticsearch restart
  - sudo apt-get install python2.7
install:
  - pip install -r requirements.txt
  - pip2 install -r requirements.txt
  - pip2 install -r scrapers/tumblr/requirements.txt
  - pip install -r scrapers/Spacebattles/requirements_linux.txt
before_script:
  - sleep 10
  - psql -c 'CREATE DATABASE noveltorpedo;' -U postgres
  - python website/manage.py migrate
  - python website/manage.py update_index
script:
  - cd website && python manage.py test
  - cd -
  - python2 website/manage.py test scrapers/tumblr
  - cd -
  - cd scrapers/Spacebattles $$ python tests/test_onepage.py && python tests/test_twopage.py

